language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# install xmllint
before_install:
   - sudo apt-get -qq update
   - sudo apt-get install -y libxml2-utils #libxml2-dev libxslt-dev python-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - make test
